name: Deploy PHP site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4 # or the version you are using

      - name: Install dependencies
        run: composer install --no-progress

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Deploy to Server
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -c "
          open ftp://$FTP_USERNAME:$FTP_PASSWORD@$FTP_SERVER;
          mirror -R . /htdocs;
          "
